## docker-compose file that spins up a omar-ai-desktop container
## and a postgres container. omar-ai-ui and omar-ai-agent are not included
## in this file, and can be run separately using npm, allowing for
## easier local development.

name: omar-ai

services:
  omar-ai-desktop:
    # Build from source
    build:
      context: ../packages/
      dockerfile: omar-aid/Dockerfile
    # Use pre-built image
    image: ghcr.io/omar-ai-ai/omar-ai-desktop:edge
    shm_size: "2g"
    container_name: omar-ai-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990" # omar-aid service & noVNC
    environment:
      - DISPLAY=:0
    networks:
      - omar-ai-network

  postgres:
    image: postgres:16-alpine
    container_name: omar-ai-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=omar-aidb
    networks:
      - omar-ai-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  omar-ai-network:
    driver: bridge

volumes:
  postgres_data:
